#!/bin/bash

wifiname=`/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | \
  awk '/ SSID/ {print substr($0, index($0, $2))}'`
echo 'Current connected wifi: ' $wifiname
security find-generic-password -a "$wifiname" -g | tail -0
