#!/bin/sh
ip=$1

if [ -z $ip ]; then
    
    read -p "请输入IP地址或域名：" ip
    ping $ip | while read pong; do echo "$(date):$pong"; done

else

    ping $ip | while read pong; do echo "$(date):$pong"; done

fi


